# A: All-Encompassing
AGeneral: &AGeneral
   - A_Journals

# B: Boiler Island
BCartTrackAboveWater: []
BCartCave: []
BTerrainOuter: []
BDomePipe: []
BTerrainInner: []
BLakeArea: []
BBoilerOutlet: []
BTerrainPath: []
BYtramCave: []
BFiremarbleCave: []
BBridgeCave: []
BBoilerToTempleBridge: []
BYtramDuct: []
BOfficeExterior: []
BOfficeInterior: []
BMagLevDock: []

# S: Shared
SRivenBase: &SRivenBase
   - S_Lighting_Riven
   - S_PostProcessing_Riven
   - S_Ocean_Riven

# G: Garden Island
   # Bases
GBase: &GBase
   - *AGeneral
   - *SRivenBase
GUpsideBase: &GUpsideBase
   - G_Terrain
   - G_WahrkTankUpper
   - G_BubbleGarden
   - G_Connector

   # Specifics
GUpsideExterior:
   - *GBase
   - *GUpsideBase
   - G_SpikeGarden
GUpsideInterior:
   - *GBase
   - *GUpsideBase
   - G_MaglevDock_B
GDownside:
   - *GBase
   - G_MaglevDock_J
   - G_WahrkTankLower

# T: Temple Island
   # Bases
TBase: &TBase
   - *AGeneral
   - *SRivenBase
   - T_Terrain

   # Specifics
TWestSide:
   - *TBase
   - S_GreatBridge
   - T_SuperDome

TNorthSide:
   - *TBase
   - S_GreatBridge
   - T_Backstage
   - T_GateRoom
   - T_SuperDome

TFissureDistrict:
   - *TBase
   - T_Backstage
   - T_GateRoom
   - T_Plateaus
   - T_NewTempleArea
   - T_SuperDome

TSpiderTunnelDistrict:
   - *TBase
   - T_GateRoom
   - T_Plateaus
   - T_NewTempleArea
   - S_Maglev_TJ
   - T_SuperDome # Ideally can split this, so it's just the superdome exterior